"""Development/production HTTP server for the gvar inspection tool.

Uses only the Python standard library for HTTP; all font math lives in the
``vfont`` package.  Endpoints:

* GET  /api/info                         -> font metadata
* POST /api/instance   {"gid": int,      -> full per-point report
                        "location": {tag: value}}
* POST /api/load       raw TTF body      -> load a new font (octet-stream)
* GET  /...                              -> static built frontend assets

The default font is the small test font regenerated by the (test-only)
fontTools builder, so the app works out of the box.
"""
from __future__ import annotations

import json
import os
import sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

HERE = os.path.dirname(__file__)
sys.path.insert(0, HERE)

from vfont import VariationEngine, VariationEngineError  # noqa: E402

STATIC_DIR = os.path.join(HERE, "..", "frontend", "dist")
MAX_UPLOAD = 8 * 1024 * 1024

# A single in-memory engine; replaced by POST /api/load.
_ENGINE: VariationEngine | None = None


def default_engine() -> VariationEngine:
    global _ENGINE
    if _ENGINE is None:
        sys.path.insert(0, os.path.join(HERE, "tests"))
        from make_fonts import build_font

        _ENGINE = VariationEngine(build_font())
    return _ENGINE


CONTENT_TYPES = {
    ".html": "text/html; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".svg": "image/svg+xml",
    ".ico": "image/x-icon",
}


class Handler(BaseHTTPRequestHandler):
    server_version = "GvarInspector/1.0"

    def log_message(self, fmt, *args):  # quieter logs
        sys.stderr.write("%s - %s\n" % (self.address_string(), fmt % args))

    # ------------------------------------------------------------------
    def _send_json(self, payload, status=200):
        body = json.dumps(payload, default=_json_default).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _send_error_json(self, message, status=400):
        self._send_json({"error": str(message)}, status=status)

    # ------------------------------------------------------------------
    def do_GET(self):
        path = self.path.split("?", 1)[0]
        if path == "/api/info":
            try:
                self._send_json(default_engine().font_info())
            except VariationEngineError as exc:
                self._send_error_json(exc)
            return
        self._serve_static(path)

    def do_POST(self):
        path = self.path.split("?", 1)[0]
        length = int(self.headers.get("Content-Length", 0))
        if length > MAX_UPLOAD:
            self._send_error_json("upload too large", 413)
            return
        raw = self.rfile.read(length) if length else b""

        if path == "/api/load":
            if not raw:
                self._send_error_json("empty font body")
                return
            try:
                global _ENGINE
                _ENGINE = VariationEngine(raw)
                self._send_json({
                    "ok": True,
                    "info": _ENGINE.font_info(),
                })
            except (VariationEngineError, ValueError, KeyError, IndexError) as exc:
                _ENGINE = None
                self._send_error_json(f"could not load font: {exc}")
            return

        if path == "/api/instance":
            try:
                request = json.loads(raw.decode("utf-8"))
            except (ValueError, UnicodeDecodeError) as exc:
                self._send_error_json(f"bad JSON: {exc}")
                return
            try:
                gid = int(request["gid"])
                location = {
                    str(k): float(v) for k, v in request.get("location", {}).items()
                }
                result = default_engine().instance(location, gid)
                self._send_json(result)
            except VariationEngineError as exc:
                self._send_error_json(exc)
            except (KeyError, TypeError, ValueError) as exc:
                self._send_error_json(f"bad request: {exc}")
            return

        self._send_error_json("not found", 404)

    # ------------------------------------------------------------------
    def _serve_static(self, path):
        if path in ("", "/"):
            path = "/index.html"
        # Prevent path traversal.
        relative = path.lstrip("/")
        full = os.path.normpath(os.path.join(STATIC_DIR, relative))
        if not full.startswith(os.path.normpath(STATIC_DIR)):
            self._send_error_json("forbidden", 403)
            return
        if not os.path.isfile(full):
            # SPA fallback.
            full = os.path.join(STATIC_DIR, "index.html")
        if not os.path.isfile(full):
            self._send_error_json("frontend not built (run npm build)", 404)
            return
        ext = os.path.splitext(full)[1]
        with open(full, "rb") as f:
            body = f.read()
        self.send_response(200)
        self.send_header(
            "Content-Type", CONTENT_TYPES.get(ext, "application/octet-stream")
        )
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def _json_default(obj):
    if isinstance(obj, (tuple, set, frozenset)):
        return list(obj)
    return str(obj)


def main():
    port = int(os.environ.get("PORT", "8000"))
    httpd = ThreadingHTTPServer(("0.0.0.0", port), Handler)
    print(f"gvar inspector on http://localhost:{port}", flush=True)
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
